version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Build phase"
artifacts:
  files:
    - appspec.yml
    - scripts/**
    - app/**              
  discard-paths: no

